# Where should we write the GIF?
Output demo.gif

# Set up a 1200x600 terminal with 46px font.
# You'll likely want to add a Margin + MarginFill if you use BorderRadius.
Set Margin 20
Set MarginFill "#674EFF"
Set BorderRadius 10
Set FontSize 46
Set Width 800
Set Height 200
Set TypingSpeed 0.1
Set Framerate 60

# Type a command in the terminal.
Type "Hello, I'm Chuck!"

# Pause for dramatic effect...
Sleep 3s

Backspace 17